;;; doom-numenor-theme.el --- Numenorean blue and gold -*- lexical-binding: t; no-byte-compile: t; -*-

(require 'doom-themes)

(def-doom-theme doom-numenor
  "A restrained blue-black theme with gold and sea-steel accents."
  :family 'doom-numenor
  :background-mode 'dark

  ((bg         '("#08111F" "black"       "black"))
   (fg         '("#EEF2F6" "#eeeeee"     "brightwhite"))
   (bg-alt     '("#101C2C" "#1e1e1e"     "black"))
   (fg-alt     '("#A8B4C3" "#b2b2b2"     "white"))

   (base0      '("#050B14" "black"       "black"))
   (base1      '("#08111F" "#080808"     "black"))
   (base2      '("#0C1725" "#121212"     "brightblack"))
   (base3      '("#101C2C" "#1c1c1c"     "brightblack"))
   (base4      '("#17283D" "#262626"     "brightblack"))
   (base5      '("#27374A" "#3a3a3a"     "brightblack"))
   (base6      '("#7D8A9B" "#808080"     "brightblack"))
   (base7      '("#C9D3DE" "#d0d0d0"     "white"))
   (base8      '("#FFFFFF" "#ffffff"     "brightwhite"))

   (grey       base5)
   (red        '("#B94747" "#af5f5f"     "red"))
   (orange     '("#D6AE4A" "#d7af5f"     "brightred"))
   (green      '("#5F9C83" "#5f9f87"     "green"))
   (teal       '("#79AFC7" "#87afaf"     "brightgreen"))
   (yellow     '("#D6AE4A" "#d7af5f"     "yellow"))
   (blue       '("#4C83C3" "#5f87af"     "brightblue"))
   (dark-blue  '("#17283D" "#1c1c5f"     "blue"))
   (magenta    '("#4C83C3" "#5f87af"     "magenta"))
   (violet     '("#79AFC7" "#87afaf"     "brightmagenta"))
   (cyan       '("#79AFC7" "#87afaf"     "brightcyan"))
   (dark-cyan  '("#4C83C3" "#5f87af"     "cyan"))

   (highlight      cyan)
   (vertical-bar   base5)
   (selection      base4)
   (builtin        cyan)
   (comments       base6)
   (doc-comments   fg-alt)
   (constants      cyan)
   (functions      cyan)
   (keywords       blue)
   (methods        cyan)
   (operators      fg-alt)
   (type           yellow)
   (strings        green)
   (variables      fg)
   (numbers        yellow)
   (region         base4)
   (error          red)
   (warning        yellow)
   (success        green)
   (vc-modified    yellow)
   (vc-added       green)
   (vc-deleted     red)

   (modeline-bg          bg-alt)
   (modeline-bg-inactive bg)
   (modeline-fg          fg)
   (modeline-fg-alt      base6))

  (((line-number &override) :foreground base6 :background bg)
   ((line-number-current-line &override) :foreground cyan :background bg-alt :weight 'bold)
   (cursor :background yellow)
   (fringe :background bg :foreground base5)
   (hl-line :background bg-alt)
   (mode-line :background modeline-bg :foreground modeline-fg :box nil)
   (mode-line-inactive :background modeline-bg-inactive :foreground modeline-fg-alt :box nil)
   (mode-line-emphasis :foreground fg :weight 'bold)
   (header-line :background bg-alt :foreground fg-alt :box nil)
   (vertical-border :foreground base5)
   (window-divider :foreground base5)
   (window-divider-first-pixel :foreground base5)
   (window-divider-last-pixel :foreground base5)
   (minibuffer-prompt :foreground cyan :weight 'bold)
   (link :foreground cyan :underline t)
   (link-visited :foreground violet :underline t)
   (show-paren-match :foreground bg :background yellow :weight 'bold)
   (isearch :foreground bg :background yellow :weight 'bold)
   (lazy-highlight :foreground bg :background cyan)
   (match :foreground bg :background yellow :weight 'bold)
   (tooltip :foreground fg :background bg-alt)
   (child-frame-border :background yellow)

   (font-lock-comment-face :foreground comments :slant 'italic)
   (font-lock-doc-face :foreground doc-comments :slant 'italic)
   (font-lock-keyword-face :foreground keywords :weight 'bold)
   (font-lock-function-name-face :foreground functions)
   (font-lock-type-face :foreground type)
   (font-lock-string-face :foreground strings)
   (font-lock-number-face :foreground numbers)
   (font-lock-variable-name-face :foreground variables)
   (font-lock-constant-face :foreground constants)
   (font-lock-builtin-face :foreground builtin)
   (font-lock-preprocessor-face :foreground yellow)
   (font-lock-warning-face :foreground warning :weight 'bold)

   (vertico-current :foreground fg :background base4 :weight 'bold)
   (corfu-default :foreground fg :background bg-alt)
   (corfu-current :foreground fg :background blue :weight 'bold)
   (corfu-border :background base5)
   (corfu-annotations :foreground fg-alt)

   (doom-modeline-bar :background blue)
   (doom-modeline-buffer-file :foreground fg :weight 'bold)
   (doom-modeline-buffer-path :foreground fg-alt)
   (doom-modeline-project-root-dir :foreground cyan :weight 'bold)
   (doom-modeline-info :foreground cyan)
   (doom-modeline-warning :foreground yellow)
   (doom-modeline-urgent :foreground red)

   (treemacs-window-background-face :background bg-alt)
   (treemacs-root-face :foreground yellow :weight 'bold)
   (treemacs-directory-face :foreground cyan)
   (treemacs-directory-collapsed-face :foreground cyan)
   (treemacs-file-face :foreground fg)
   (treemacs-git-modified-face :foreground yellow)
   (treemacs-git-untracked-face :foreground green)
   (treemacs-git-added-face :foreground green)
   (treemacs-git-conflict-face :foreground red :weight 'bold)
   (treemacs-hl-line-face :background base4)

   (demap-minimap-font-face :family "Hack" :height 30 :foreground fg-alt :background bg-alt)
   (demap-visible-region-face :background base4 :extend t)
   (demap-visible-region-inactive-face :background base3 :extend t)
   (demap-current-line-face :background blue :foreground fg :extend t)
   (demap-current-line-inactive-face :background blue :foreground fg :extend t)

   (+dashboard-banner :foreground fg-alt)
   (+dashboard-menu-title :foreground cyan :weight 'bold)
   (+dashboard-menu-desc :foreground fg)
   (+dashboard-footer :foreground fg-alt)
   (+dashboard-loaded :foreground fg-alt)

   (markdown-header-face :foreground cyan :weight 'bold)
   (markdown-code-face :background bg-alt)
   (markdown-markup-face :foreground base6)
   (org-level-1 :foreground cyan :weight 'bold)
   (org-level-2 :foreground cyan :weight 'bold)
   (org-level-3 :foreground blue :weight 'bold)
   (org-code :foreground green)
   (org-block :background bg-alt)
   (org-block-begin-line :foreground base6 :background bg-alt)
   (org-block-end-line :foreground base6 :background bg-alt))

  ())

;;; doom-numenor-theme.el ends here
